# Generated by Codex on 2026-07-03

import uuid

import django.db.models.deletion
from django.db import migrations, models

import plane.db.models.analytic


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0122_issue_datetime_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagementAnalyticsSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("config", models.JSONField(default=plane.db.models.analytic.get_default_management_analytics_config)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to="db.user",
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to="db.user",
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="management_analytics_settings",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Management Analytics Settings",
                "verbose_name_plural": "Management Analytics Settings",
                "db_table": "management_analytics_settings",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="issueactivity",
            index=models.Index(fields=["workspace", "field", "created_at"], name="issueact_ws_field_created_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["workspace", "state", "target_date"], name="issue_ws_state_target_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["workspace", "completed_at"], name="issue_ws_completed_idx"),
        ),
    ]
