# Generated by Codex on 2026-07-14

from django.db import migrations, models


SUPER_ADMIN_EMAILS = {
    "propandamen@gmail.com",
    "vsevolodkargashin2408@gmail.com",
}


def grant_initial_super_admins(apps, schema_editor):
    WorkspaceMember = apps.get_model("db", "WorkspaceMember")
    Project = apps.get_model("db", "Project")
    ProjectMember = apps.get_model("db", "ProjectMember")
    ProjectUserProperty = apps.get_model("db", "ProjectUserProperty")

    memberships = WorkspaceMember.objects.filter(
        member__email__in=SUPER_ADMIN_EMAILS,
        is_active=True,
        deleted_at__isnull=True,
    ).select_related("member", "workspace")

    for workspace_member in memberships:
        WorkspaceMember.objects.filter(pk=workspace_member.pk).update(role=30)
        for project in Project.objects.filter(
            workspace_id=workspace_member.workspace_id,
            archived_at__isnull=True,
            deleted_at__isnull=True,
        ):
            project_member = ProjectMember.objects.filter(
                project_id=project.id,
                member_id=workspace_member.member_id,
                deleted_at__isnull=True,
            ).first()
            if project_member is None:
                ProjectMember.objects.create(
                    workspace_id=workspace_member.workspace_id,
                    project_id=project.id,
                    member_id=workspace_member.member_id,
                    role=20,
                    is_active=True,
                    is_super_admin_access=True,
                )
            elif not project_member.is_active:
                ProjectMember.objects.filter(pk=project_member.pk).update(is_active=True)

            if not ProjectUserProperty.objects.filter(
                project_id=project.id,
                user_id=workspace_member.member_id,
                deleted_at__isnull=True,
            ).exists():
                ProjectUserProperty.objects.create(
                    workspace_id=workspace_member.workspace_id,
                    project_id=project.id,
                    user_id=workspace_member.member_id,
                )


def noop_reverse(apps, schema_editor):
    # Role assignment is intentionally not reversed automatically: a rollback
    # must never silently revoke leadership access in a live workspace.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0123_management_analytics_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="is_super_admin_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="workspacemember",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(30, "OG"), (20, "Admin"), (15, "Member"), (5, "Guest")],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="workspacememberinvite",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(30, "OG"), (20, "Admin"), (15, "Member"), (5, "Guest")],
                default=5,
            ),
        ),
        migrations.RunPython(grant_initial_super_admins, noop_reverse),
    ]
