# Generated by Django 4.2.30 on 2026-09-14 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_recurring_issue_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='issue_placements_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='IssuePlacement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sequence_id', models.PositiveBigIntegerField()),
                ('sort_order', models.FloatField(default=65535)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_placements', to='db.state')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'issue_placements',
            },
        ),
        migrations.AddConstraint(
            model_name='issueplacement',
            constraint=models.UniqueConstraint(fields=('issue', 'project'), name='issue_placement_unique_project'),
        ),
        migrations.AddConstraint(
            model_name='issueplacement',
            constraint=models.UniqueConstraint(fields=('project', 'sequence_id'), name='issue_placement_unique_number'),
        ),
    ]
