# Generated by Django 4.2.30 on 2026-09-28 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0128_issue_comment_reads'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotState',
            fields=[
                ('bot_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offset', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(null=True, unique=True)),
                ('telegram_name', models.CharField(blank=True, max_length=255)),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('blocked_at', models.DateTimeField(null=True)),
                ('token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('token_expires_at', models.DateTimeField(null=True)),
                ('pending_id', models.BigIntegerField(null=True)),
                ('pending_name', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('assignments', models.BooleanField(default=True)),
                ('mentions', models.BooleanField(default=True)),
                ('replies', models.BooleanField(default=True)),
                ('comments', models.BooleanField(default=True)),
                ('watching', models.BooleanField(default=False)),
                ('scheduled', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64)),
                ('weekdays_only', models.BooleanField(default=True)),
                ('start_hour', models.PositiveSmallIntegerField(default=10)),
                ('end_hour', models.PositiveSmallIntegerField(default=19)),
                ('paused_until', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telegram_connections',
            },
        ),
        migrations.CreateModel(
            name='TelegramDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(db_index=True, null=True)),
                ('status', models.CharField(default='sending', max_length=20)),
                ('message_id', models.BigIntegerField(null=True)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='db.telegramconnection')),
            ],
            options={
                'db_table': 'telegram_deliveries',
            },
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_replies', to='db.issuecomment'),
        ),
        migrations.CreateModel(
            name='TelegramMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.telegramconnection')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.issue')),
            ],
            options={
                'db_table': 'telegram_mutes',
            },
        ),
        migrations.CreateModel(
            name='TelegramEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dedup_key', models.CharField(max_length=120)),
                ('kind', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.issueactivity')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.issuecomment')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='db.telegramconnection')),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='db.telegramdelivery')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.issue')),
            ],
            options={
                'db_table': 'telegram_events',
            },
        ),
        migrations.AddConstraint(
            model_name='telegrammute',
            constraint=models.UniqueConstraint(fields=('connection', 'issue'), name='telegram_mute_unique'),
        ),
        migrations.AddConstraint(
            model_name='telegramevent',
            constraint=models.UniqueConstraint(fields=('connection', 'dedup_key'), name='telegram_event_dedup'),
        ),
    ]
