# Generated by Django 4.2.30 on 2026-10-02 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.board_link


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0129_telegram_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardLink',
            fields=[
                ('token', models.CharField(default=plane.db.models.board_link.board_link_token, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('filters', models.JSONField(default=dict)),
                ('display', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_links', to='db.cycle')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_links', to='db.project')),
            ],
            options={
                'db_table': 'board_links',
            },
        ),
    ]
