# Generated by Django 4.2.30 on 2026-10-02 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0130_board_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitLabIntegration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('base_url', models.URLField(max_length=500)),
                ('name', models.CharField(default='GitLab', max_length=200)),
                ('token_encrypted', models.TextField()),
                ('webhook_secret_encrypted', models.TextField()),
                ('client_id', models.TextField(blank=True)),
                ('client_secret_encrypted', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gitlab_integrations', to='db.workspace')),
            ],
            options={
                'db_table': 'gitlab_integrations',
                'unique_together': {('workspace', 'base_url')},
            },
        ),
        migrations.CreateModel(
            name='GitLabRepository',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('gitlab_id', models.BigIntegerField()),
                ('path', models.CharField(max_length=1000)),
                ('web_url', models.URLField(max_length=1500)),
                ('enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='db.gitlabintegration')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'gitlab_repositories',
                'unique_together': {('integration', 'gitlab_id')},
            },
        ),
        migrations.CreateModel(
            name='GitLabObject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('kind', models.CharField(choices=[('mr', 'mr'), ('commit', 'commit'), ('pipeline', 'pipeline'), ('job', 'job')], max_length=20)),
                ('external_id', models.CharField(max_length=128)),
                ('data', models.JSONField(default=dict)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='db.gitlabrepository')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'gitlab_objects',
                'unique_together': {('repository', 'kind', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='GitLabWebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.gitlabintegration')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.gitlabrepository')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'gitlab_webhook_events',
                'unique_together': {('integration', 'fingerprint')},
            },
        ),
        migrations.CreateModel(
            name='GitLabUserConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('gitlab_user_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=255)),
                ('token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('redirect_uri', models.URLField(blank=True, max_length=1500)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_connections', to='db.gitlabintegration')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gitlab_user_connections',
                'unique_together': {('integration', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GitLabObjectRelation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='db.gitlabobject')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relations', to='db.gitlabobject')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'gitlab_object_relations',
                'unique_together': {('parent', 'child')},
            },
        ),
        migrations.CreateModel(
            name='GitLabIssueLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('origins', models.JSONField(default=list)),
                ('suppressed', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gitlab_links', to='db.issue')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='db.gitlabobject')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'gitlab_issue_links',
                'unique_together': {('issue', 'object')},
            },
        ),
        migrations.CreateModel(
            name='GitLabDiagnostic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('marker', models.CharField(max_length=80)),
                ('external_id', models.CharField(max_length=128)),
                ('kind', models.CharField(max_length=20)),
                ('code', models.CharField(default='issue_not_found', max_length=40)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.gitlabrepository')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'gitlab_diagnostics',
                'unique_together': {('repository', 'marker', 'external_id', 'kind')},
            },
        ),
    ]
