# Generated by Django 4.2.30 on 2026-10-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0131_gitlab_development'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabrepository',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
