# Generated by Django 4.2.30 on 2026-10-02 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0132_gitlab_reconciliation_cursor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabobject',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_objects', to='db.gitlabrepository'),
        ),
    ]
