# Generated by Django 4.2.30 on 2026-10-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0133_gitlab_repository_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabrepository',
            name='error_code',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
