# Generated by Django 4.2.30 on 2026-10-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0135_gitlab_oauth_attempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitlabrepository",
            name="discovery_heads",
            field=models.JSONField(default=dict),
        ),
    ]
