# Generated by Django 4.2.30 on 2026-10-09 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0137_gitlab_branch_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='sort_order',
            field=models.FloatField(default=65535),
        ),
        migrations.CreateModel(
            name='PageFolder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.FloatField(default=65535)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='db.pagefolder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_folders', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_folders', to='db.workspace')),
            ],
            options={
                'db_table': 'page_folders',
                'ordering': ('sort_order', 'name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='projectpage',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_pages', to='db.pagefolder'),
        ),
        migrations.AddIndex(
            model_name='pagefolder',
            index=models.Index(fields=['project', 'parent'], name='page_folder_project_parent_idx'),
        ),
    ]
