# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only

from django.db import transaction
from django.utils import timezone


SUPER_ADMIN_ROLE = 30
PROJECT_ADMIN_ROLE = 20


@transaction.atomic
def grant_workspace_super_admin_access(workspace, member):
    """Grant implicit admin membership to every project in a workspace."""
    from plane.db.models import Project, ProjectMember

    for project in Project.objects.filter(workspace=workspace, archived_at__isnull=True):
        membership = ProjectMember.objects.filter(project=project, member=member).first()
        if membership:
            if not membership.is_active:
                membership.is_active = True
                membership.save(update_fields=["is_active", "updated_at"])
            continue

        # Reuse a soft-deleted membership instead of creating a duplicate. A
        # ProjectMember creates a ProjectUserProperty on first save, so blindly
        # recreating it can violate that property's uniqueness constraint when
        # the super-admin role is granted for a second time.
        membership = (
            ProjectMember.all_objects.filter(project=project, member=member)
            .order_by("-created_at")
            .first()
        )
        if membership:
            membership.deleted_at = None
            membership.is_active = True
            membership.role = PROJECT_ADMIN_ROLE
            membership.is_super_admin_access = True
            membership.save(
                update_fields=[
                    "deleted_at",
                    "is_active",
                    "role",
                    "is_super_admin_access",
                    "updated_at",
                ]
            )
            continue

        ProjectMember.objects.create(
            workspace=workspace,
            project=project,
            member=member,
            role=PROJECT_ADMIN_ROLE,
            is_active=True,
            is_super_admin_access=True,
        )


@transaction.atomic
def revoke_workspace_super_admin_access(workspace, member):
    """Revoke only memberships that were generated by the super-admin role."""
    from plane.db.models import ProjectMember

    ProjectMember.objects.filter(
        workspace=workspace,
        member=member,
        is_super_admin_access=True,
        is_active=True,
    ).update(is_active=False, deleted_at=timezone.now(), updated_at=timezone.now())


@transaction.atomic
def grant_project_access_to_workspace_super_admins(project):
    """Make a newly-created project immediately visible to all super admins."""
    from plane.db.models import ProjectMember, WorkspaceMember

    super_admin_ids = WorkspaceMember.objects.filter(
        workspace=project.workspace,
        role=SUPER_ADMIN_ROLE,
        is_active=True,
    ).values_list("member_id", flat=True)
    for member_id in super_admin_ids:
        if ProjectMember.objects.filter(project=project, member_id=member_id).exists():
            continue
        ProjectMember.objects.create(
            workspace=project.workspace,
            project=project,
            member_id=member_id,
            role=PROJECT_ADMIN_ROLE,
            is_active=True,
            is_super_admin_access=True,
        )
