export type TGitLabKind = "branch" | "mr" | "commit" | "pipeline" | "job";
export type TGitLabIntegration = {
  id: string;
  name: string;
  base_url: string;
  enabled: boolean;
  status: string;
  error_code: string;
  last_synced_at: string | null;
  user_connected: boolean;
  username: string | null;
  oauth_configured: boolean;
  repository_ids?: number[];
  client_id?: string;
  webhook_url?: string;
  callback_url?: string;
};
export type TGitLabObject = {
  id: string;
  kind: TGitLabKind;
  external_id: string;
  repository_id: string;
  repository: string;
  synced_at: string;
  data: {
    title?: string | null;
    message?: string | null;
    author_name?: string | null;
    source_branch?: string | null;
    target_branch?: string | null;
    name?: string | null;
    protected?: boolean | null;
    default?: boolean | null;
    stage?: string | null;
    duration?: number | null;
    state?: string | null;
    status?: string | null;
    source?: string | null;
    ref?: string | null;
    tag?: boolean | null;
    sha?: string | null;
    pipeline_id?: number | null;
    web_url?: string | null;
    created_at?: string | null;
    started_at?: string | null;
    updated_at?: string | null;
    committed_date?: string | null;
    retried?: boolean;
    allow_failure?: boolean;
  };
};
export type TGitLabDevelopment = {
  integrations: TGitLabIntegration[];
  access_errors: string[];
  objects: TGitLabObject[];
  relations: { parent: string; child: string; created_at: string }[];
  links: { id: string; object_id: string; origins: string[]; pinned: boolean; created_at: string }[];
};
export type TGitLabAction = "add" | "pin" | "unpin" | "unlink" | "restore";
export type TGitLabMutation = { action: TGitLabAction; url?: string; object_id?: string };
export type TGitLabConfiguration = {
  id?: string;
  base_url: string;
  name: string;
  token?: string;
  repository_ids: number[];
  client_id?: string;
  client_secret?: string;
  enabled: boolean;
};
